### ISSUE TITLE
Missing codewars.com API

### ISSUE THREAD

**Issue by nemtsov** [nemtsov/codewars#1]
@nathandoctor @jhoffner (bump)

**Comment by jhoffner** [comment]
Hi Yuriy. Sorry for the delay on this. We have been going through some growing pains, but this task is actually next up in the queue for one of our new developers and shouldn't take much longer. 

Also you can check out the [codewars-cli](http://github.com/codewars/codewars-cli) project that we just recently pushed. That one was created to make adding language support easier, and is meant to be used by our (still a work in progress) sandboxing process but can also be used to support our test framework customizations offline. Looks like these two could integration well. Both are written in Node.  You could include one within the other.
